name: db-compose
services:
  # Postgres database
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  # DB management interface
  adminer:
    image: adminer
    restart: always
    ports:
      - "8888:8080"